import { getDb } from '@/database/db';
import { enqueueSync } from '@/database/queue';
import { newId, nowIso } from '@/utils/id';
import type { PantryItem, Task, Bill, Device } from '@/types/models';

export async function listPantry(householdId: string): Promise<PantryItem[]> { const db = await getDb(); return db.getAllAsync('SELECT * FROM pantry_items WHERE household_id=? ORDER BY name', householdId); }
export async function addPantry(householdId: string, name: string): Promise<void> { const db=await getDb(); const id=newId('pantry'), now=nowIso(); const p={id,household_id:householdId,name:name.trim(),quantity:1,minimum_quantity:0,created_at:now,updated_at:now}; await db.runAsync('INSERT INTO pantry_items(id,household_id,name,quantity,minimum_quantity,created_at,updated_at) VALUES(?,?,?,?,?,?,?)',id,householdId,p.name,1,0,now,now); await enqueueSync('pantry_items',id,'CREATE',p); }
export async function listTasks(householdId: string): Promise<Task[]> { const db=await getDb(); return db.getAllAsync('SELECT * FROM tasks WHERE household_id=? ORDER BY completed, due_date IS NULL, due_date, created_at DESC',householdId); }
export async function addTask(householdId:string,title:string):Promise<void>{const db=await getDb();const id=newId('task'),now=nowIso();const p={id,household_id:householdId,title:title.trim(),completed:false,created_at:now,updated_at:now};await db.runAsync('INSERT INTO tasks(id,household_id,title,completed,created_at,updated_at) VALUES(?,?,?,?,?,?)',id,householdId,p.title,0,now,now);await enqueueSync('tasks',id,'CREATE',p);}
export async function toggleTask(id:string,completed:boolean):Promise<void>{const db=await getDb();const now=nowIso();await db.runAsync('UPDATE tasks SET completed=?, completed_at=?, updated_at=? WHERE id=?',completed?1:0,completed?now:null,now,id);await enqueueSync('tasks',id,'UPDATE',{completed,completed_at:completed?now:null,updated_at:now});}
export async function listBills(householdId:string):Promise<Bill[]>{const db=await getDb();return db.getAllAsync('SELECT * FROM bills WHERE household_id=? ORDER BY status, due_date',householdId);}
export async function addBill(householdId:string,title:string,amount:number,dueDate:string):Promise<void>{const db=await getDb();const id=newId('bill'),now=nowIso();const p={id,household_id:householdId,title:title.trim(),amount,due_date:dueDate,status:'open',created_at:now,updated_at:now};await db.runAsync(`INSERT INTO bills(id,household_id,title,amount,due_date,status,created_at,updated_at) VALUES(?,?,?,?,?,'open',?,?)`,id,householdId,p.title,amount,dueDate,now,now);await enqueueSync('bills',id,'CREATE',p);}
export async function listDevices(householdId:string):Promise<Device[]>{const db=await getDb();return db.getAllAsync('SELECT * FROM devices WHERE household_id=? ORDER BY name',householdId);}
export async function addDevice(householdId:string,name:string):Promise<void>{const db=await getDb();const id=newId('device'),now=nowIso();const p={id,household_id:householdId,name:name.trim(),created_at:now,updated_at:now};await db.runAsync('INSERT INTO devices(id,household_id,name,created_at,updated_at) VALUES(?,?,?,?,?)',id,householdId,p.name,now,now);await enqueueSync('devices',id,'CREATE',p);}
