import { useEffect,useState } from 'react';
import { Alert,Pressable,StyleSheet,Text,TextInput,View } from 'react-native';
import Ionicons from '@expo/vector-icons/Ionicons';
import { Screen } from '@/components/Screen';
import { EmptyState } from '@/components/EmptyState';
import { addPantry,addTask,listPantry,listTasks,toggleTask } from '@/repositories/homeRepo';
import type{PantryItem,Task}from '@/types/models';
import { useAppStore } from '@/store/appStore';
import { colors,radius,spacing } from '@/theme/theme';
import { isBelowMinimum } from '@/utils/rules';

export default function Home(){
 const hh=useAppStore(s=>s.activeHouseholdId),bump=useAppStore(s=>s.bump);const[mode,setMode]=useState<'pantry'|'task'>('pantry');const[text,setText]=useState('');const[pantry,setPantry]=useState<PantryItem[]>([]);const[tasks,setTasks]=useState<Task[]>([]);const[busy,setBusy]=useState(false);
 const load=async()=>{if(!hh)return;const[p,t]=await Promise.all([listPantry(hh),listTasks(hh)]);setPantry(p);setTasks(t)};
 useEffect(()=>{void load().catch(e=>Alert.alert('Laden fehlgeschlagen',e instanceof Error?e.message:'Unbekannter Fehler'));},[hh]);
 const add=async()=>{if(!hh||!text.trim()||busy)return;setBusy(true);try{mode==='pantry'?await addPantry(hh,text.trim()):await addTask(hh,text.trim());setText('');await load();bump()}catch(e){Alert.alert('Speichern fehlgeschlagen',e instanceof Error?e.message:'Unbekannter Fehler')}finally{setBusy(false)}};
 const open=tasks.filter(t=>!t.completed).length,low=pantry.filter(p=>isBelowMinimum(p.quantity,p.minimum_quantity)).length;
 return <Screen><View style={s.hero}><View><Text style={s.kicker}>HAUSHALT</Text><Text style={s.h1}>Zuhause</Text><Text style={s.sub}>{pantry.length} Vorräte · {open} Aufgaben</Text></View><View style={s.heroIcon}><Ionicons name="home-outline" size={25} color={colors.accent}/></View></View><View style={s.segment}>{(['pantry','task'] as const).map(x=><Pressable key={x} onPress={()=>setMode(x)} style={[s.seg,mode===x&&s.segOn]}><Ionicons name={x==='pantry'?'cube-outline':'checkmark-circle-outline'} size={18} color={mode===x?colors.accentText:colors.textMuted}/><Text style={[s.segText,mode===x&&s.segTextOn]}>{x==='pantry'?'Vorrat':'Aufgaben'}</Text>{(x==='pantry'?low:open)>0?<Text style={[s.badge,mode===x&&s.badgeOn]}>{x==='pantry'?low:open}</Text>:null}</Pressable>)}</View><View style={s.add}><TextInput style={s.input} placeholder={mode==='pantry'?'Vorrat hinzufügen':'Aufgabe hinzufügen'} placeholderTextColor={colors.textSoft} value={text} onChangeText={setText} onSubmitEditing={()=>void add()}/><Pressable disabled={!text.trim()||busy} onPress={()=>void add()} style={[s.plus,(!text.trim()||busy)&&s.disabled]}><Ionicons name="add" size={26} color="#fff"/></Pressable></View>{mode==='pantry'?(pantry.length?pantry.map(p=><View key={p.id} style={s.row}><View style={[s.icon,isBelowMinimum(p.quantity,p.minimum_quantity)&&s.warnIcon]}><Ionicons name="cube-outline" size={19} color={isBelowMinimum(p.quantity,p.minimum_quantity)?colors.warning:colors.accent}/></View><View style={s.flex}><Text style={s.name}>{p.name}</Text><Text style={s.meta}>{p.quantity} {p.unit??'Stk.'} · Minimum {p.minimum_quantity}</Text></View>{isBelowMinimum(p.quantity,p.minimum_quantity)?<Text style={s.warn}>Nachkaufen</Text>:null}</View>):<EmptyState icon="cube-outline" title="Vorrat ist leer" body="Füge Lebensmittel oder Haushaltsartikel hinzu."/>):(tasks.length?tasks.map(t=><Pressable key={t.id} onPress={()=>void(async()=>{try{await toggleTask(t.id,!t.completed);await load();bump()}catch(e){Alert.alert('Fehler',e instanceof Error?e.message:'Änderung fehlgeschlagen')}})()} style={s.row}><View style={[s.check,t.completed===1&&s.checkOn]}>{t.completed?<Ionicons name="checkmark" size={17} color="#fff"/>:null}</View><View style={s.flex}><Text style={[s.name,t.completed===1&&s.done]}>{t.title}</Text><Text style={s.meta}>{t.due_date?`Fällig ${t.due_date}`:'Keine Fälligkeit'}</Text></View></Pressable>):<EmptyState icon="checkmark-done-outline" title="Keine Aufgaben" body="Füge eine neue Aufgabe hinzu."/>)}</Screen>
}
const s=StyleSheet.create({hero:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},kicker:{fontSize:11,fontWeight:'800',letterSpacing:1,color:colors.textMuted},h1:{fontSize:35,lineHeight:41,fontWeight:'800',letterSpacing:-1.1,color:colors.text},sub:{fontSize:15,color:colors.textMuted},heroIcon:{width:50,height:50,borderRadius:17,backgroundColor:colors.accentSoft,alignItems:'center',justifyContent:'center'},segment:{flexDirection:'row',padding:4,gap:4,borderRadius:radius.md,backgroundColor:colors.surfaceMuted},seg:{flex:1,minHeight:46,borderRadius:14,flexDirection:'row',gap:7,alignItems:'center',justifyContent:'center'},segOn:{backgroundColor:colors.accent},segText:{fontSize:14,fontWeight:'700',color:colors.textMuted},segTextOn:{color:'#fff'},badge:{fontSize:11,fontWeight:'800',color:colors.warning,backgroundColor:colors.warningSoft,paddingHorizontal:6,paddingVertical:3,borderRadius:10},badgeOn:{color:'#fff',backgroundColor:'rgba(255,255,255,.18)'},add:{flexDirection:'row',gap:spacing.sm,backgroundColor:colors.surface,padding:12,borderRadius:radius.lg,borderWidth:1,borderColor:colors.border},input:{flex:1,minHeight:50,borderRadius:radius.md,backgroundColor:colors.surfaceMuted,paddingHorizontal:14,fontSize:16,color:colors.text},plus:{width:50,height:50,borderRadius:radius.md,backgroundColor:colors.accent,alignItems:'center',justifyContent:'center'},disabled:{opacity:.4},row:{minHeight:68,flexDirection:'row',alignItems:'center',gap:12,padding:13,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,backgroundColor:colors.surface},icon:{width:40,height:40,borderRadius:13,backgroundColor:colors.accentSoft,alignItems:'center',justifyContent:'center'},warnIcon:{backgroundColor:colors.warningSoft},check:{width:30,height:30,borderRadius:10,borderWidth:2,borderColor:colors.border,alignItems:'center',justifyContent:'center'},checkOn:{backgroundColor:colors.accent,borderColor:colors.accent},flex:{flex:1},name:{fontSize:15,fontWeight:'700',color:colors.text},meta:{fontSize:12,color:colors.textMuted,marginTop:3},warn:{fontSize:11,fontWeight:'800',color:colors.warning},done:{textDecorationLine:'line-through',color:colors.textMuted}});
